databases:
  - name: teramon_DB
    databaseName: teramon_db
    user: teramon
    region: singapore

services:
  - type: web
    name: teramon
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teramon_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
